apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: inlets-operator
    git:
      url: https://github.com/inlets/inlets-operator
      ref: 0.7.3
    includePaths:
    - artifacts/*

