apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: contour
    git:
      url: https://github.com/projectcontour/contour
      ref: v1.4.0
    includePaths:
    - examples/contour/*
  - path: metallb
    git:
      url: https://github.com/metallb/metallb
      ref: v0.9.3
    includePaths:
    - manifests/*
  - path: inlets-operator
    git:
      url: https://github.com/inlets/inlets-operator
      ref: 0.7.3
    includePaths:
    - artifacts/*
  - path: nfs-client-provisioner
    manual: {}
  - path: kube-state-metrics
    manual: {}
- path: build/nfs-client-provisioner/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      ref: a0fcd60856902429e3369f243414233d2923122c # version 1.2.8
    includePaths:
    - stable/nfs-client-provisioner/**/*
- path: build/kube-state-metrics/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      ref: 329944ed63ead692e3d6aa5081306aa57785da6f # version 2.8.4
    includePaths:
    - stable/kube-state-metrics/**/*