apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: contour
    git:
      url: https://github.com/projectcontour/contour
      ref: v1.4.0
    includePaths:
    - examples/contour/*
  - path: inlets-operator
    git:
      url: https://github.com/inlets/inlets-operator
      ref: 0.7.3
    includePaths:
    - artifacts/*
  - path: nfs-client-provisioner
    manual: {}
- path: build/nfs-client-provisioner/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      ref: a0fcd60856902429e3369f243414233d2923122c # version 1.2.8
    includePaths:
    - stable/nfs-client-provisioner/**/*