#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Secret
metadata:
  name: inlets-access-key
  namespace: inlets
type: Opaque
data:
  inlets-access-key: #@ base64.encode(data.values.digitalocean_access_token)